### ACCOUNT

### List
GET /api/admin/channel/list HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A

### Add
POST /api/admin/channel/add HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A
Content-Type: application/json

{
    "title": "test",
    "url_image": "www.google.com.br"
}

### Find
POST /api/admin/channel/get/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A

### Update
POST /api/admin/channel/update HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A
Content-Type: application/json

{
    "id": 1,
    "title": "channel 1",
    "url_image": "www.google.com.br"
}

### Remove
POST /api/admin/channel/remove/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A

### Permanently Delete
POST /api/admin/channel/delete/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoia2VsdmluLm1lbmVnYXNzZUBmcmFuY29kYXJvY2hhLnNwLmdvdi5iciIsImxldmVsIjoiYWRtaW5pc3RyYXRvciIsInJlbWVtYmVyIjpmYWxzZSwicm53IjoxNjAyNDcxMDI4LCJpYXQiOjE1OTk4NDMwMjgsImV4cCI6MTYwMjQ3MTAyOH0.scv3MGm9HBtWwT6zX8h0bVummgiPj6QqRXYDwC2po6A